name: Build Automake

on:
  push:
    branches:
        - branchAutomake

jobs:
  build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Install dependencies
          run: sudo apt-get update && sudo apt-get install -y automake autoconf

        - name: Build project
          run: |
            autoreconf --install
            ./configure
            make

        - name: Create tarball
          run: make dist
